name: Update HTML Page

on:
  schedule:
    # Run every hour at minutes 5, 20, 35, 50
    - cron: "5,20,35,50 * * * *"
  push:
    branches:
      - main # also trigger on pushes to main

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run update script
        run: |
          python update_html.py

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add index.html
          git commit -m "Update HTML file" || echo "No changes to commit"
          git push

      # Optionally deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
